package com.test.dto;

/**
 * 考试信息dto,原有考试信息的基础上加上pName(试卷名)
 * 
 * @author lt
 *
 */
public class ExamInfo {
	

	private Integer eId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam.e_name
	 *
	 * @mbggenerated Thu May 10 09:23:26 CST 2018
	 */
	private String eName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam.p_id
	 *
	 * @mbggenerated Thu May 10 09:23:26 CST 2018
	 */
	private Integer pId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam.e_time
	 *
	 * @mbggenerated Thu May 10 09:23:26 CST 2018
	 */
	private Integer eTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam.stu_list
	 *
	 * @mbggenerated Thu May 10 09:23:26 CST 2018
	 */
	private String stuList;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam.c_score
	 *
	 * @mbggenerated Thu May 10 09:23:26 CST 2018
	 */
	private Integer cScore;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam.dc_score
	 *
	 * @mbggenerated Thu May 10 09:23:26 CST 2018
	 */
	private Integer dcScore;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam.j_score
	 *
	 * @mbggenerated Thu May 10 09:23:26 CST 2018
	 */
	private Integer jScore;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam.f_score
	 *
	 * @mbggenerated Thu May 10 09:23:26 CST 2018
	 */
	private Integer fScore;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam.a_score
	 *
	 * @mbggenerated Thu May 10 09:23:26 CST 2018
	 */
	private Integer aScore;

	private String pName;

	public Integer geteId() {
		return eId;
	}

	public void seteId(Integer eId) {
		this.eId = eId;
	}

	public String geteName() {
		return eName;
	}

	public void seteName(String eName) {
		this.eName = eName;
	}

	public Integer getpId() {
		return pId;
	}

	public void setpId(Integer pId) {
		this.pId = pId;
	}

	public Integer geteTime() {
		return eTime;
	}

	public void seteTime(Integer eTime) {
		this.eTime = eTime;
	}

	public String getStuList() {
		return stuList;
	}

	public void setStuList(String stuList) {
		this.stuList = stuList;
	}

	public Integer getcScore() {
		return cScore;
	}

	public void setcScore(Integer cScore) {
		this.cScore = cScore;
	}

	public Integer getDcScore() {
		return dcScore;
	}

	public void setDcScore(Integer dcScore) {
		this.dcScore = dcScore;
	}

	public Integer getjScore() {
		return jScore;
	}

	public void setjScore(Integer jScore) {
		this.jScore = jScore;
	}

	public Integer getfScore() {
		return fScore;
	}

	public void setfScore(Integer fScore) {
		this.fScore = fScore;
	}

	public Integer getaScore() {
		return aScore;
	}

	public void setaScore(Integer aScore) {
		this.aScore = aScore;
	}

	public String getpName() {
		return pName;
	}

	public void setpName(String pName) {
		this.pName = pName;
	}

	@Override
	public String toString() {
		return "ExamInfo [eId=" + eId + ", eName=" + eName + ", pId=" + pId + ", eTime=" + eTime + ", stuList="
				+ stuList + ", cScore=" + cScore + ", dcScore=" + dcScore + ", jScore=" + jScore + ", fScore=" + fScore
				+ ", aScore=" + aScore + ", pName=" + pName + "]";
	}

}