package com.test.dto;

public class GradeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.id
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.stu_no
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    private String stuNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.e_id
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    private Integer eId;
    private String eName;
    
    
    public String geteName() {
		return eName;
	}

	public void seteName(String eName) {
		this.eName = eName;
	}
	
	private Integer pId;
    private String pName;
	

	public Integer getpId() {
		return pId;
	}

	public void setpId(Integer pId) {
		this.pId = pId;
	}

	public String getpName() {
		return pName;
	}

	public void setpName(String pName) {
		this.pName = pName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.obj_score
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    private Integer objScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.sub_score
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    private Integer subScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.total_score
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    private Integer totalScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.is_marked
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    private Integer isMarked;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.id
     *
     * @return the value of grade.id
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.id
     *
     * @param id the value for grade.id
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.stu_no
     *
     * @return the value of grade.stu_no
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    public String getStuNo() {
        return stuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.stu_no
     *
     * @param stuNo the value for grade.stu_no
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    public void setStuNo(String stuNo) {
        this.stuNo = stuNo == null ? null : stuNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.e_id
     *
     * @return the value of grade.e_id
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.e_id
     *
     * @param eId the value for grade.e_id
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.obj_score
     *
     * @return the value of grade.obj_score
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    public Integer getObjScore() {
        return objScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.obj_score
     *
     * @param objScore the value for grade.obj_score
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    public void setObjScore(Integer objScore) {
        this.objScore = objScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.sub_score
     *
     * @return the value of grade.sub_score
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    public Integer getSubScore() {
        return subScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.sub_score
     *
     * @param subScore the value for grade.sub_score
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    public void setSubScore(Integer subScore) {
        this.subScore = subScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.total_score
     *
     * @return the value of grade.total_score
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    public Integer getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.total_score
     *
     * @param totalScore the value for grade.total_score
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    public void setTotalScore(Integer totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.is_marked
     *
     * @return the value of grade.is_marked
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    public Integer getIsMarked() {
        return isMarked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.is_marked
     *
     * @param isMarked the value for grade.is_marked
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    public void setIsMarked(Integer isMarked) {
        this.isMarked = isMarked;
    }

	@Override
	public String toString() {
		return "GradeInfo [id=" + id + ", stuNo=" + stuNo + ", eId=" + eId + ", eName=" + eName + ", pId=" + pId
				+ ", pName=" + pName + ", objScore=" + objScore + ", subScore=" + subScore + ", totalScore="
				+ totalScore + ", isMarked=" + isMarked + "]";
	}
    
}