package com.test.domain;

public class Exam {

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.e_id
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    private Integer eId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.e_name
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    private String eName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.p_id
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.e_time
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    private Integer eTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.stu_list
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    private String stuList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.c_score
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    private Integer cScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.dc_score
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    private Integer dcScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.j_score
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    private Integer jScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.f_score
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    private Integer fScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.a_score
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    private Integer aScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.e_id
     *
     * @return the value of exam.e_id
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.e_id
     *
     * @param eId the value for exam.e_id
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.e_name
     *
     * @return the value of exam.e_name
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public String geteName() {
        return eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.e_name
     *
     * @param eName the value for exam.e_name
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public void seteName(String eName) {
        this.eName = eName == null ? null : eName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.p_id
     *
     * @return the value of exam.p_id
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.p_id
     *
     * @param pId the value for exam.p_id
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.e_time
     *
     * @return the value of exam.e_time
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public Integer geteTime() {
        return eTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.e_time
     *
     * @param eTime the value for exam.e_time
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public void seteTime(Integer eTime) {
        this.eTime = eTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.stu_list
     *
     * @return the value of exam.stu_list
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public String getStuList() {
        return stuList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.stu_list
     *
     * @param stuList the value for exam.stu_list
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public void setStuList(String stuList) {
        this.stuList = stuList == null ? null : stuList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.c_score
     *
     * @return the value of exam.c_score
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public Integer getcScore() {
        return cScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.c_score
     *
     * @param cScore the value for exam.c_score
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public void setcScore(Integer cScore) {
        this.cScore = cScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.dc_score
     *
     * @return the value of exam.dc_score
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public Integer getDcScore() {
        return dcScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.dc_score
     *
     * @param dcScore the value for exam.dc_score
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public void setDcScore(Integer dcScore) {
        this.dcScore = dcScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.j_score
     *
     * @return the value of exam.j_score
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public Integer getjScore() {
        return jScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.j_score
     *
     * @param jScore the value for exam.j_score
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public void setjScore(Integer jScore) {
        this.jScore = jScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.f_score
     *
     * @return the value of exam.f_score
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public Integer getfScore() {
        return fScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.f_score
     *
     * @param fScore the value for exam.f_score
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public void setfScore(Integer fScore) {
        this.fScore = fScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.a_score
     *
     * @return the value of exam.a_score
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public Integer getaScore() {
        return aScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.a_score
     *
     * @param aScore the value for exam.a_score
     *
     * @mbggenerated Thu May 10 09:23:26 CST 2018
     */
    public void setaScore(Integer aScore) {
        this.aScore = aScore;
    }

	@Override
	public String toString() {
		return "Exam [eId=" + eId + ", eName=" + eName + ", pId=" + pId + ", eTime=" + eTime + ", stuList=" + stuList
				+ ", cScore=" + cScore + ", dcScore=" + dcScore + ", jScore=" + jScore + ", fScore=" + fScore
				+ ", aScore=" + aScore + "]";
	}
    
    
}