package com.test.domain;

public class Paper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.p_id
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.p_name
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    private String pName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.p_id
     *
     * @return the value of paper.p_id
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.p_id
     *
     * @param pId the value for paper.p_id
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.p_name
     *
     * @return the value of paper.p_name
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.p_name
     *
     * @param pName the value for paper.p_name
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

	@Override
	public String toString() {
		return "Paper [pId=" + pId + ", pName=" + pName + "]";
	}
    
}