package com.test.domain;

public class Question {
	
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.q_Id
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    private Integer qId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.q_Content
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    private String qContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.q_Answer
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    private String qAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.q_Type
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    private String qType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.q_Id
     *
     * @return the value of question.q_Id
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public Integer getqId() {
        return qId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.q_Id
     *
     * @param qId the value for question.q_Id
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public void setqId(Integer qId) {
        this.qId = qId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.q_Content
     *
     * @return the value of question.q_Content
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public String getqContent() {
        return qContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.q_Content
     *
     * @param qContent the value for question.q_Content
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public void setqContent(String qContent) {
        this.qContent = qContent == null ? null : qContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.q_Answer
     *
     * @return the value of question.q_Answer
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public String getqAnswer() {
        return qAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.q_Answer
     *
     * @param qAnswer the value for question.q_Answer
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public void setqAnswer(String qAnswer) {
        this.qAnswer = qAnswer == null ? null : qAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.q_Type
     *
     * @return the value of question.q_Type
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public String getqType() {
        return qType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.q_Type
     *
     * @param qType the value for question.q_Type
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public void setqType(String qType) {
        this.qType = qType == null ? null : qType.trim();
    }

	@Override
	public String toString() {
		return "Question [qId=" + qId + ", qContent=" + qContent + ", qAnswer=" + qAnswer + ", qType=" + qType + "]";
	}
    
}