package com.test.domain;

public class QuestionAndPaper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_paper.id
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_paper.q_id
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    private Integer qId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_paper.p_id
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    private Integer pId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_paper.id
     *
     * @return the value of question_paper.id
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_paper.id
     *
     * @param id the value for question_paper.id
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_paper.q_id
     *
     * @return the value of question_paper.q_id
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public Integer getqId() {
        return qId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_paper.q_id
     *
     * @param qId the value for question_paper.q_id
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public void setqId(Integer qId) {
        this.qId = qId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_paper.p_id
     *
     * @return the value of question_paper.p_id
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_paper.p_id
     *
     * @param pId the value for question_paper.p_id
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }
}