package com.test.domain;

public class StuLogin {
    @Override
	public String toString() {
		return "StuLogin [stuNo=" + stuNo + ", password=" + password + ", status=" + status + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_login.stu_no
     *
     * @mbggenerated Mon May 07 13:24:54 CST 2018
     */
    private String stuNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_login.password
     *
     * @mbggenerated Mon May 07 13:24:54 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_login.status
     *
     * @mbggenerated Mon May 07 13:24:54 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_login.stu_no
     *
     * @return the value of stu_login.stu_no
     *
     * @mbggenerated Mon May 07 13:24:54 CST 2018
     */
    public String getStuNo() {
        return stuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_login.stu_no
     *
     * @param stuNo the value for stu_login.stu_no
     *
     * @mbggenerated Mon May 07 13:24:54 CST 2018
     */
    public void setStuNo(String stuNo) {
        this.stuNo = stuNo == null ? null : stuNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_login.password
     *
     * @return the value of stu_login.password
     *
     * @mbggenerated Mon May 07 13:24:54 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_login.password
     *
     * @param password the value for stu_login.password
     *
     * @mbggenerated Mon May 07 13:24:54 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_login.status
     *
     * @return the value of stu_login.status
     *
     * @mbggenerated Mon May 07 13:24:54 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_login.status
     *
     * @param status the value for stu_login.status
     *
     * @mbggenerated Mon May 07 13:24:54 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}