package com.test.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.test.domain.Grade;
import com.test.dto.GradeInfo;
import com.test.dto.StuGrade;

public interface GradeMapper {
	
	
	List<StuGrade> selectByCond(@Param("eId")String eId,@Param("stuClass")String stuClass,@Param("searchCond")String searchCond,@Param("searchText")String searchText);
	
	
	List<GradeInfo> getGrade(String stuNo);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    int insert(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    int insertSelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    Grade selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    int updateByPrimaryKeySelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    int updateByPrimaryKey(Grade record);
}