package com.test.dao;

import com.test.domain.PaperAnswer;

public interface PaperAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_answer
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_answer
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    int insert(PaperAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_answer
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    int insertSelective(PaperAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_answer
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    PaperAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_answer
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    int updateByPrimaryKeySelective(PaperAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper_answer
     *
     * @mbggenerated Sat May 12 10:23:37 CST 2018
     */
    int updateByPrimaryKey(PaperAnswer record);
}