package com.test.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.test.domain.Paper;

public interface PaperMapper {
	
	
	/**
	 * 按条件分页查询
	 * 
	 * @param searchText
	 * @return
	 */
	List<Paper> selectPaperByCond(@Param("searchText")String searchText);
	
	
	/**
	 * 获取所有试卷信息
	 * @return
	 */
	List<Paper> selectAll();
	
	
	/**
	 * 按试卷名搜索试卷
	 * 
	 * @param pName
	 * @return
	 */
	Paper selectByPName(String pName);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    int deleteByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    int insert(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    int insertSelective(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    Paper selectByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    int updateByPrimaryKeySelective(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paper
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    int updateByPrimaryKey(Paper record);
}