package com.test.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.test.domain.Question;
import com.test.domain.QuestionInfo;

public interface QuestionMapper {

	/**
	 * 按条件分页查询
	 * 
	 * @param qType
	 * @param pName
	 * @param searchText
	 * @return
	 */
	List<QuestionInfo> selectQInfo(@Param("qType") String qType, @Param("pName") String pName,
			@Param("searchText") String searchText);
	
	
	List<Question> selectAll();
	
	/**
	 * 获取主键
	 * 
	 * @return
	 */
	Integer getQId();
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table question
	 *
	 * @mbggenerated Tue Apr 24 18:48:58 CST 2018
	 */
	int deleteByPrimaryKey(Integer qId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table question
	 *
	 * @mbggenerated Tue Apr 24 18:48:58 CST 2018
	 */
	int insert(Question record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table question
	 *
	 * @mbggenerated Tue Apr 24 18:48:58 CST 2018
	 */
	int insertSelective(Question record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table question
	 *
	 * @mbggenerated Tue Apr 24 18:48:58 CST 2018
	 */
	Question selectByPrimaryKey(Integer qId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table question
	 *
	 * @mbggenerated Tue Apr 24 18:48:58 CST 2018
	 */
	int updateByPrimaryKeySelective(Question record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table question
	 *
	 * @mbggenerated Tue Apr 24 18:48:58 CST 2018
	 */
	int updateByPrimaryKey(Question record);

}