package com.test.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.test.domain.QuestionAndPaper;

public interface QuestionAndPaperMapper {
	
	// 按试题qId 删除
	int deleteByQId(Integer qId);
	
	// 按qId / pId 删除 试题和试卷之间的联系
	int deleteByQIdAndPId(@Param("qId") Integer qId,@Param("pId") Integer pId);
	
	// 按试卷id查询
	List<QuestionAndPaper> selectByPId(int pId);
	
	
	// 按试卷id删除
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_paper
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_paper
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    int insert(QuestionAndPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_paper
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    int insertSelective(QuestionAndPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_paper
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    QuestionAndPaper selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_paper
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    int updateByPrimaryKeySelective(QuestionAndPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_paper
     *
     * @mbggenerated Tue Apr 24 18:48:58 CST 2018
     */
    int updateByPrimaryKey(QuestionAndPaper record);
}